# Generated by Django 4.1.1 on 2022-10-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppF1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitos',
            name='año_primer_carrera',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuitos',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='circuitos',
            name='país',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='constructores',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='constructores',
            name='nacionalidad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='constructores',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pilotos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilotos',
            name='nacionalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pilotos',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
